# Generated by Django 4.2.3 on 2024-02-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_registration_token_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.TextField(
                choices=[
                    ("COMPANY_EMPLOYEE", "Company employee"),
                    ("FREELANCER", "Freelancer"),
                    ("COMPANY", "Company"),
                    ("EMPLOYEE", "Employee"),
                ],
                editable=False,
                null=True,
            ),
        ),
    ]
