# Generated by Django 4.2.3 on 2024-02-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="token",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
