# Generated by Django 4.2.3 on 2024-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvite",
            name="token",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
