# Generated by Django 4.2.3 on 2024-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userinvite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.TextField(
                choices=[
                    ("ADMINISTRATOR", "Administrator"),
                    ("COMPANY_EMPLOYEE", "Company employee"),
                    ("FREELANCER", "Freelancer"),
                    ("COMPANY", "Company"),
                    ("EMPLOYEE", "Employee"),
                ],
                editable=False,
                null=True,
            ),
        ),
    ]
