# Generated by Django 4.2.3 on 2024-03-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_information", models.TextField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        null=True,
                        upload_to='apps.accounts.models.upload_to_profile_folder',
                    ),
                ),
                (
                    "company_file",
                    models.FileField(
                        upload_to='apps.accounts.models.upload_to_profile_folder'
                    ),
                ),
                (
                    "contact_name_and_position",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
