# Generated by Django 4.2.3 on 2024-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_profile_company_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company_phone",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
