# Generated by Django 4.2.3 on 2024-04-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_stripe_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
