# Generated by Django 4.2.3 on 2024-04-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_user_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
