# Generated by Django 4.2.3 on 2024-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_delete_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company",
            new_name="_company",
        ),
    ]
