# Generated by Django 4.2.3 on 2024-04-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_rename_company_user__company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="_company",
            new_name="rel_company",
        ),
    ]
