# Generated by Django 4.2.3 on 2024-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.TextField(
                choices=[
                    ("ADMINISTRATOR", "Administrator"),
                    ("COMPANY_EMPLOYEE", "Company employee"),
                    ("FREELANCER", "Freelancer"),
                    ("COMPANY", "Company"),
                    ("EMPLOYEE", "Employee"),
                ],
                null=True,
            ),
        ),
    ]
