# Generated by Django 4.2.3 on 2024-10-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "English"),
                    ("DUTCH", "Dutch"),
                    ("GERMAN", "German"),
                    ("HUNGARIAN", "Hungarian"),
                ],
                default="ENGLISH",
            ),
        ),
    ]
