# Generated by Django 5.1 on 2025-04-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_companyinvite_delete_userinvite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyInvite",
        ),
    ]
