# Generated by Django 5.1 on 2025-04-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_delete_companyinvite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
