# Generated by Django 5.1 on 2025-04-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.TextField(
                choices=[
                    ("ADMINISTRATOR", "Administrator"),
                    ("FREELANCER", "Freelancer"),
                    ("COMPANY", "Company"),
                    ("EMPLOYEE", "Employee"),
                ],
                null=True,
            ),
        ),
    ]
