#!/bin/bash

# set -o errexit
# set -o pipefail
# set -o nounset

# # Migrate, cache table, majd futtatás
# python manage.py migrate
# python manage.py createcachetable

# exec python manage.py runserver 0.0.0.0:8000



set -o errexit
set -o pipefail
set -o nounset

# Alap dolgok, ha elfelejtenéd
python manage.py migrate
python manage.py createcachetable
python manage.py collectstatic --noinput

# Production WSGI szerver indítása
exec gunicorn config.wsgi:application \
    --bind 0.0.0.0:8000 \
    --workers 3 \
    --timeout 120 \
    --log-level info \
    --access-logfile - \
    --error-logfile -
