# Generated by Django 4.2.3 on 2024-03-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                ("job_title", models.CharField(max_length=355)),
                ("job_description", models.TextField()),
                ("expectations", models.TextField()),
                ("educations", models.TextField()),
                ("language_knowledge", models.TextField()),
                ("driving_licence", models.TextField()),
                ("advantages", models.TextField()),
                (
                    "working_time",
                    models.CharField(
                        choices=[
                            ("FULL TIME", "Full time"),
                            ("PART TIME", "Part time"),
                            ("REMOTE WORK", "Remote work"),
                            ("HOME OFFICE", "Home office"),
                            ("CASUAL", "Casual"),
                            ("PROFESSIONAL PRACTICE", "Professional practice"),
                            ("STUDENT WORK", "Student work"),
                            (
                                "FOR MOTHERS AND / OR SINGLE PARENTS",
                                "For mother and / or single parents",
                            ),
                            (
                                "IN PENSION, WORK NEXT TO RETIRED",
                                "In pension, work next to retired",
                            ),
                            (
                                "FOR CHANGED EMPLOYMENT CAPACITY",
                                "For changed employment capacity",
                            ),
                        ]
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        choices=[
                            ("GENERAL WORKING SCHEDULE", "GENERAL WORKING SCHEDULE"),
                            ("2 SHIFTS", "2 SHIFTS"),
                            ("3 SHIFTS", "3 SHIFTS"),
                            ("12/48 SHIFT", "12/48 SHIFT"),
                            ("12/24 SHIFT", "12/24 SHIFT"),
                            (
                                "24/72 SHIFT, STANDBY SERVICE",
                                "24/72 SHIFT, STANDBY SERVICE",
                            ),
                            ("FLEXIBILE", "FLEXIBILE"),
                            ("CONTINUOUS WORKING TIME", "CONTINUOUS WORKING TIME"),
                            ("OPTIONAL WORKING HOURS", "OPTIONAL WORKING HOURS"),
                        ]
                    ),
                ),
                ("work_place_address", models.CharField(max_length=254)),
                ("work_place_city", models.CharField(max_length=254)),
                ("work_place_country", models.CharField(max_length=254)),
                ("benefits", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
