# Generated by Django 4.2.3 on 2024-03-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="language_knowledge",
        ),
        migrations.CreateModel(
            name="RequiredLanguageKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=255)),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ]
                    ),
                ),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_languages",
                        to="job_post.jobpost",
                    ),
                ),
            ],
        ),
    ]
