# Generated by Django 4.2.3 on 2024-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0002_remove_jobpost_language_knowledge_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="job_title",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="title",
            field=models.CharField(default="pék", max_length=254),
            preserve_default=False,
        ),
    ]
