# Generated by Django 4.2.3 on 2024-03-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0003_remove_jobpost_job_title_jobpost_slug_jobpost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="contact_email",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobpost",
            name="contact_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobpost",
            name="contact_phone",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_contact_email_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_contact_name_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_contact_phone_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_cover_letter_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_cv_required",
            field=models.BooleanField(default=False),
        ),
    ]
