# Generated by Django 4.2.3 on 2024-04-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0004_jobpost_contact_email_jobpost_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requiredlanguageknowledge",
            name="language",
            field=models.CharField(
                choices=[
                    ("Arabic", "Arabic"),
                    ("Bengali", "Bengali"),
                    ("Bulgarian", "Bulgarian"),
                    ("Chinese", "Chinese"),
                    ("Croatian", "Croatian"),
                    ("Czech", "Czech"),
                    ("Danish", "Danish"),
                    ("Dutch", "Dutch"),
                    ("English", "English"),
                    ("Estonian", "Estonian"),
                    ("Finnish", "Finnish"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Greek", "Greek"),
                    ("Hindi", "Hindi"),
                    ("Hungarian", "Hungarian"),
                    ("Irish", "Irish"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Latvian", "Latvian"),
                    ("Lithuanian", "Lithuanian"),
                    ("Malay", "Malay"),
                    ("Maltese", "Maltese"),
                    ("Polish", "Polish"),
                    ("Portuguese", "Portuguese"),
                    ("Punjabi", "Punjabi"),
                    ("Romanian", "Romanian"),
                    ("Slovak", "Slovak"),
                    ("Slovenian", "Slovenian"),
                    ("Spanish", "Spanish"),
                    ("Swedish", "Swedish"),
                    ("Urdu", "Urdu"),
                ]
            ),
        ),
    ]
