# Generated by Django 4.2.3 on 2024-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0005_alter_requiredlanguageknowledge_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="driving_licence",
            field=models.TextField(
                choices=[
                    ("B", "B"),
                    ("BE", "BE"),
                    ("A", "A"),
                    ("A1", "A1"),
                    ("C1", "C1"),
                    ("C1E", "C1E"),
                    ("CE", "CE"),
                    ("D1", "D1"),
                    ("D1E", "D1E"),
                    ("D", "D"),
                    ("DE", "DE"),
                ]
            ),
        ),
    ]
