# Generated by Django 4.2.3 on 2024-04-15 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_post", "0006_alter_jobpost_driving_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
