# Generated by Django 4.2.3 on 2024-04-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0007_jobpost_saved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="job_category",
            field=models.CharField(
                choices=[
                    ("ENGINEERING", "engineering"),
                    ("EDUCATION", "education"),
                    ("CONSTRUCTION", "construction"),
                ],
                default="ENGINEERING",
            ),
            preserve_default=False,
        ),
    ]
