# Generated by Django 4.2.3 on 2024-04-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0008_jobpost_job_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="job_category",
            field=models.CharField(
                choices=[
                    ("ENGINEERING", "engineering"),
                    ("EDUCATION", "education"),
                    ("CONSTRUCTION", "construction"),
                    ("ACCOUNTANCY", "accountancy"),
                    ("APPRENTICESHIP", "apprenticeship"),
                    ("BANKING", "banking"),
                    ("REAL_ESTATE", "real estate"),
                    ("IT_AND_TELCO", "It & Telco"),
                    ("LEGAL", "legal"),
                ]
            ),
        ),
    ]
