# Generated by Django 4.2.3 on 2024-04-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0009_alter_jobpost_job_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("GENERAL WORKING SCHEDULE", "GENERAL WORKING SCHEDULE"),
                    ("2 SHIFTS", "2 SHIFTS"),
                    ("3 SHIFTS", "3 SHIFTS"),
                    ("12/48 SHIFT", "12/48 SHIFT"),
                    ("12/24 SHIFT", "12/24 SHIFT"),
                    ("24/72 SHIFT, STANDBY SERVICE", "24/72 SHIFT, STANDBY SERVICE"),
                    ("FLEXIBLE", "FLEXIBLE"),
                    ("CONTINUOUS WORKING TIME", "CONTINUOUS WORKING TIME"),
                    ("OPTIONAL WORKING HOURS", "OPTIONAL WORKING HOURS"),
                    ("STUDENT WORK", "STUDENT WORK"),
                    (
                        "FOR MOTHERS AND/OR SINGLE PARENTS",
                        "FOR MOTHERS AND/OR SINGLE PARENTS",
                    ),
                    (
                        "IN PENSION, WORK NEXT TO RETIRED",
                        "IN PENSION, WORK NEXT TO RETIRED",
                    ),
                    (
                        "FOR CHANGED EMPLOYMENT CAPACITY",
                        "FOR CHANGED EMPLOYMENT CAPACITY",
                    ),
                ]
            ),
        ),
    ]
