# Generated by Django 4.2.3 on 2024-04-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0010_alter_jobpost_work_schedule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="job_category",
            new_name="industry",
        ),
    ]
