# Generated by Django 4.2.3 on 2024-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0011_rename_job_category_jobpost_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="educations",
            field=models.CharField(
                choices=[
                    ("ELEMENTARY", "Elementary"),
                    ("SECONDARY", "Secondary"),
                    ("HIGHSCHOOL", "HighSchool"),
                    ("BSC", "Bsc"),
                    ("MSC", "Msc"),
                    ("PHD", "Phd"),
                ]
            ),
        ),
    ]
