# Generated by Django 4.2.3 on 2024-04-30 11:12

import apps.job_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0013_jobpostapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostapplication",
            name="cover_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.job_post.models.upload_to_job_post_folder,
            ),
        ),
        migrations.AlterField(
            model_name="jobpostapplication",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.job_post.models.upload_to_job_post_folder,
            ),
        ),
    ]
