# Generated by Django 4.2.3 on 2024-05-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0014_alter_jobpostapplication_cover_letter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubIndustryChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(choices=[("C#", "C#"), ("JAVA", "Java")])),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_industry_choices",
                        to="job_post.jobpost",
                    ),
                ),
            ],
        ),
    ]
