# Generated by Django 4.2.3 on 2024-05-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0015_subindustrychoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subindustrychoice",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_industries",
                to="job_post.jobpost",
            ),
        ),
    ]
