# Generated by Django 4.2.3 on 2024-05-15 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0016_alter_subindustrychoice_job_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="industry",
            field=models.CharField(
                choices=[
                    ("AGRICULTURE_ENVIRONMENT", "Agriculture, Environment"),
                    ("BANK_INSURANCE_BROKER", "Bank, Insurance, Broker"),
                    ("ENGINEERING", "Engineering"),
                    ("CONSTRUCTION", "Construction"),
                    ("EDUCATION", "Education"),
                    ("ACCOUNTANCY", "Accountancy"),
                    ("APPRENTICESHIP", "Apprenticeship"),
                    ("BANKING", "Banking"),
                    ("REAL_ESTATE", "Real Estate"),
                    ("IT_AND_TELCO", "IT & Telco"),
                    ("LEGAL", "Legal"),
                    ("TECHNOLOGY", "Technology"),
                    ("HEALTHCARE", "Healthcare"),
                    ("FINANCE", "Finance"),
                    ("RETAIL", "Retail"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("TRANSPORTATION", "Transportation"),
                    ("ENERGY", "Energy"),
                    ("GOVERNMENT", "Government"),
                    ("HOSPITALITY", "Hospitality"),
                    ("MEDIA", "Media"),
                    ("NONPROFIT", "Nonprofit"),
                    ("ARTS_ENTERTAINMENT", "Arts & Entertainment"),
                    ("SCIENCE_RESEARCH", "Science & Research"),
                    ("CUSTOMER_SERVICE", "Customer Relation, Customer Service"),
                    ("SUPPLY_CHAIN", "Supply Chain, Acquisition"),
                    ("HUMAN_RESOURCES", "Human Resources, Labor Case, Labor Supply"),
                    ("MARKETING", "Marketing, Media, PR, Advertisement"),
                    ("LOGISTICS", "Logistics, Duty, Customs Clearance"),
                    ("ADMINISTRATION", "Office Jobs, Administration"),
                    ("SALES", "Sales, Trade, Commerce, Economics"),
                    ("SPORT", "Sport"),
                    ("WAREHOUSE", "Warehouse"),
                    ("PUBLIC_RELATIONS", "Public Relations"),
                    (
                        "PUBLIC_ADMINISTRATION",
                        "Office Jobs, Administration",
                    ),
                    ("TRAINED_UNSKILLED_WORKERS", "Trained or Unskilled Workers"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="subindustrychoice",
            name="choice",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATION", "Administration, Administrator"),
                    ("FACTORY_WORKER", "Factory Worker"),
                    ("WASTE_MANAGEMENT", "Waste Management"),
                    ("ENVIRONMENTAL_PROTECTION", "Environmental Protection"),
                    ("ENVIRONMENTAL_SUSTAINABILITY", "Environmental Sustainability"),
                    ("PROFESSIONAL_CONSULTANT", "Professional Consultant"),
                    ("FARM_HELP", "Farm Help"),
                    ("GROWING_PLANTS", "Growing Plants"),
                    (
                        "FRUIT_VEGETABLE_PICKING",
                        "Fruits and Vegetables Picking, Harvesting",
                    ),
                    ("PRODUCTION", "Production, Product Management"),
                    ("COMPONENT_EQUIPMENT_RESOURCES", "Component, Equipment Resources"),
                    (
                        "COMPONENT_EQUIPMENT_WAREHOUSE",
                        "Component and Equipment Warehouse, Delivery",
                    ),
                    ("PRODUCT_MANAGEMENT", "Product Management, Assistant"),
                    ("SALES", "Sales, Seller, Agricultural Sales Person"),
                    ("ENGINEER", "Engineer, Food Engineer"),
                    ("MECHANICAL_ENGINEER", "Mechanical Engineer"),
                    ("QUALITY_CONTROL", "Quality, Quality Control"),
                    ("TECHNICIAN", "Technician, Experimental Technician, Consultant"),
                    ("COMMERCIAL_COORDINATOR", "Commercial Coordinator, Sales"),
                    ("REGIONAL_REPRESENTATIVE", "Regional Representative"),
                    ("LAB", "Lab, Labor"),
                    ("NATURE_CONSERVATION", "Nature Conservation Officer"),
                    ("FOREST_MANAGEMENT", "Forest Management, Forestry"),
                    (
                        "PLANT_ANIMAL_PROTECTION",
                        "Plant and Animal Protection, Agronomist",
                    ),
                    ("VETERINARIAN", "Veterinarian"),
                    ("HERBALIST", "Herbalist"),
                    ("SITE_MANAGER", "Site Manager"),
                    ("FORKLIFT_DRIVER", "Forklift Driver"),
                    (
                        "SEED_PLANT_STOREKEEPER",
                        "Seed Plant, Storekeeper, Shift Manager",
                    ),
                    ("BANK_INSURANCE_MANAGEMENT", "Bank and Insurance Management"),
                    ("INVESTMENT_ANALYST", "Investment, Investment Analyst"),
                    ("ANALYST", "Analyst"),
                    ("DATA_MINER", "Data Miner, Database Manager, SQL"),
                    ("SAP", "SAP"),
                    ("ACCOUNT", "Account, Account Management, Manager"),
                    ("BANK_CARD_MANAGEMENT", "Bank Card Management"),
                    ("CREDIT_CONTROL", "Credit, Credit Control"),
                    ("UNIVERSAL_CONSULTANT", "Universal Consultant"),
                    (
                        "PROPERTY_LIABILITY_INSURANCE",
                        "Property and Liability Insurance",
                    ),
                    ("INSURANCE", "Insurance"),
                    (
                        "PRODUCT_SPECIALIST",
                        "Product Specialist, Product Manager, Product Development Manager",
                    ),
                    ("CORPORATE_CUSTOMER_CONTACT", "Corporate Customer Contact"),
                    ("PROCESS_SPECIALIST", "Process Specialist, Process Development"),
                    ("COACH_AGILE_TEAM_LEADER", "Coach, Agile Team Leader"),
                    (
                        "BANK_INSURANCE_INFORMATICS",
                        "Bank and Insurance Informatics, Programmer",
                    ),
                    ("WEBDESIGN", "Web Design, Web Developer"),
                    ("THREE_D_DEVELOPMENT", "3D Development"),
                    ("CREDIT_RISK", "Credit Risk, Risk Controller"),
                    ("CONSULTANT", "Consultant"),
                    ("CUSTOMER_REPRESENTATIVE", "Customer Representative, CRM, CSS"),
                    (
                        "ADMINISTRATION_OFFICE_JOB",
                        "Administration, Office Job, Office Assistant",
                    ),
                    ("TELEPHONE_CLERK", "Telephone Clerk, Telephone Salesperson"),
                    ("CASHIER", "Cashier, Changer, Money Change"),
                    ("FINANCIAL_ADVISOR", "Financial Advisor"),
                    ("COMPLIANCE", "Compliance, Complaint Clerk"),
                    ("REGIONAL_REPRESENTATIVE_BANK", "Regional Representative"),
                    ("BUSINESS_MANAGER", "Business Manager"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("SECURITY", "Security"),
                    ("LOGISTICS", "Logistics, Transport, Delivery"),
                    (
                        "SMALL_BUSINESS_CONSULTANT",
                        "Small Business Consultant, Salesperson",
                    ),
                    (
                        "MEDIUM_SIZED_BUSINESS_CONSULTANT",
                        "Medium-Sized Company, Business Consultant, Salesperson",
                    ),
                    (
                        "LARGE_CORPORATE_SALES",
                        "Large Corporate Business Consultant, Salesperson",
                    ),
                    ("CLAIMS_ADJUSTER", "Claims Adjuster"),
                    (
                        "MONEY_LAUNDERING_PREVENTION",
                        "Money Laundering Prevention, Officer",
                    ),
                    ("BROKER", "Broker"),
                    ("CSHARP", "C#"),
                    ("JAVA", "Java"),
                    ("CONSTRUCTION_ENGINEER", "Construction Engineer"),
                ]
            ),
        ),
    ]
