# Generated by Django 4.2.3 on 2024-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_post",
            "0017_jobpostapplication_created_at_alter_jobpost_industry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="driving_licence",
            field=models.TextField(
                choices=[
                    ("A", "A"),
                    ("A1", "A1"),
                    ("B", "B"),
                    ("BE", "BE"),
                    ("C1", "C1"),
                    ("C1E", "C1E"),
                    ("CE", "CE"),
                    ("D", "D"),
                    ("D1", "D1"),
                    ("D1E", "D1E"),
                    ("DE", "DE"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="educations",
            field=models.CharField(
                choices=[
                    ("BSC", "Bsc"),
                    ("ELEMENTARY", "Elementary"),
                    ("HIGHSCHOOL", "HighSchool"),
                    ("MSC", "Msc"),
                    ("PHD", "Phd"),
                    ("SECONDARY", "Secondary"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="industry",
            field=models.CharField(
                choices=[
                    ("ACCOUNTANCY", "Accountancy & Finance"),
                    ("AGRICULTURE_ENVIRONMENT", "Agriculture, Environment"),
                    ("APPRENTICESHIP", "Apprenticeship, Internship"),
                    ("ARTS_ENTERTAINMENT", "Arts & Entertainment"),
                    ("BANK_INSURANCE_BROKER", "Bank, Insurance, Broker"),
                    ("CONSTRUCTION", "Construction & Building Industry"),
                    ("CUSTOMER_SERVICE", "Customer Relation, Customer Service"),
                    ("EDUCATION", "Education"),
                    ("ENERGY", "Energy"),
                    ("ENGINEERING", "Engineering"),
                    ("HEALTHCARE", "Healthcare"),
                    ("HOSPITALITY", "Hospitality & Tourism"),
                    ("HUMAN_RESOURCES", "Human Resources & Labor Case"),
                    ("IT_AND_TELCO", "IT & Telecom"),
                    ("LEGAL", "Law & Legal Cases"),
                    ("LOGISTICS", "Logistics, Duty, Customs Clearance"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("MARKETING", "Marketing, PR, Advertisement"),
                    ("MEDIA", "Media"),
                    ("NONPROFIT", "Nonprofit"),
                    ("PROJECT_MANAGEMENT", "Project Management"),
                    (
                        "PUBLIC_ADMINISTRATION",
                        "Office Jobs, Administration",
                    ),
                    ("PUBLIC_RELATIONS", "Public Relations"),
                    ("REAL_ESTATE", "Real Estate"),
                    ("RETAIL", "Retail"),
                    ("SALES", "Sales, Trade, Commerce, Economics"),
                    ("SCIENCE_RESEARCH", "Science & Research"),
                    ("SECURITY", "Security"),
                    ("SPORT", "Sport"),
                    ("SUPPLY_CHAIN", "Supply Chain & Logistics"),
                    ("TECHNOLOGY", "Technology"),
                    ("TRAINED_UNSKILLED_WORKERS", "Trained or Unskilled Jobs"),
                    ("TRANSPORTATION", "Transportation"),
                    ("WAREHOUSE", "Warehouse"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("CONTINUOUS WORKING TIME", "Continuous Working Time"),
                    ("FLEXIBLE", "Flexible"),
                    (
                        "FOR CHANGED EMPLOYMENT CAPACITY",
                        "For Changed Employment Capacity",
                    ),
                    ("GENERAL WORKING SCHEDULE", "General Working Schedule"),
                    (
                        "IN PENSION, WORK NEXT TO RETIRED",
                        "In Pension, Work Next To Retired",
                    ),
                    (
                        "FOR MOTHERS AND/OR SINGLE PARENTS",
                        "For Mothers And/or Single Parents",
                    ),
                    ("OPTIONAL WORKING HOURS", "Optional Working Hours"),
                    ("2 SHIFTS", "2 Shifts"),
                    ("3 SHIFTS", "3 Shifts"),
                    ("12/24 SHIFT", "12/24 Shifts"),
                    ("12/48 SHIFT", "12/48 Shifts"),
                    ("24/72 SHIFT, STANDBY SERVICE", "24/72 Shift, Standby Service"),
                    ("STUDENT WORK", "Student Work"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="working_time",
            field=models.CharField(
                choices=[
                    ("CASUAL", "Casual"),
                    (
                        "FOR CHANGED EMPLOYMENT CAPACITY",
                        "For changed employment capacity",
                    ),
                    (
                        "FOR MOTHERS AND / OR SINGLE PARENTS",
                        "For Mothers and / or Single Parents",
                    ),
                    ("FULL TIME", "Full time"),
                    ("HOME OFFICE", "Home office"),
                    (
                        "IN PENSION, WORK NEXT TO RETIRED",
                        "In pension, work next to retired",
                    ),
                    ("PART TIME", "Part time"),
                    ("PROFESSIONAL PRACTICE", "Professional practice"),
                    ("REMOTE WORK", "Remote work"),
                    ("STUDENT WORK", "Student work"),
                ]
            ),
        ),
    ]
