# Generated by Django 4.2.3 on 2024-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0018_alter_jobpost_driving_licence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="industry",
            field=models.CharField(
                choices=[
                    ("ACCOUNTANCY", "Accountancy & Finance"),
                    ("AGRICULTURE_ENVIRONMENT", "Agriculture, Environment"),
                    ("APPRENTICESHIP", "Apprenticeship, Internship"),
                    ("ARTS_ENTERTAINMENT", "Arts & Entertainment"),
                    ("BANK_INSURANCE_BROKER", "Bank, Insurance, Broker"),
                    ("CONSTRUCTION", "Construction & Building Industry"),
                    ("CUSTOMER_SERVICE", "Customer Relation, Customer Service"),
                    ("EDUCATION", "Education"),
                    ("ENERGY", "Energy"),
                    ("ENGINEERING", "Engineering"),
                    ("HEALTHCARE", "Healthcare"),
                    ("HOSPITALITY", "Hospitality & Tourism"),
                    ("HUMAN_RESOURCES", "Human Resources & Labor Case"),
                    ("IT_AND_TELCO", "IT & Telecom"),
                    ("LEGAL", "Law & Legal Cases"),
                    ("LOGISTICS", "Logistics, Duty, Customs Clearance"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("MARKETING", "Marketing, PR, Advertisement"),
                    ("MEDIA", "Media"),
                    ("NONPROFIT", "Nonprofit"),
                    ("PROJECT_MANAGEMENT", "Project Management"),
                    ("PUBLIC_ADMINISTRATION", "Office Jobs, Administration"),
                    ("PUBLIC_RELATIONS", "Public Relations"),
                    ("REAL_ESTATE", "Real Estate"),
                    ("RETAIL", "Retail"),
                    ("SALES", "Sales, Trade, Commerce, Economics"),
                    ("SCIENCE_RESEARCH", "Science & Research"),
                    ("SECURITY", "Security"),
                    ("SPORT", "Sport"),
                    ("SUPPLY_CHAIN", "Supply Chain & Logistics"),
                    ("TECHNOLOGY", "Technology"),
                    ("TRAINED_UNSKILLED_WORKERS", "Trained or Unskilled Jobs"),
                    ("TRANSPORTATION", "Transportation"),
                    ("WAREHOUSE", "Warehouse"),
                ]
            ),
        ),
    ]
