# Generated by Django 4.2.3 on 2024-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0019_alter_jobpost_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("CONTINUOUS WORKING TIME", "Continuous Working Time"),
                    ("FLEXIBLE", "Flexible"),
                    (
                        "FOR CHANGED EMPLOYMENT CAPACITY",
                        "For Changed Employment Capacity",
                    ),
                    ("GENERAL WORKING SCHEDULE", "General Working Schedule"),
                    (
                        "IN PENSION, WORK NEXT TO RETIRED",
                        "In Pension, Work Next To Retired",
                    ),
                    (
                        "FOR MOTHERS AND/OR SINGLE PARENTS",
                        "For Mothers And/or Single Parents",
                    ),
                    ("OPTIONAL WORKING HOURS", "Optional Working Hours"),
                    ("2 SHIFTS", "2 Shifts"),
                    ("3 SHIFTS", "3 Shifts"),
                    ("12/24 SHIFT", "12/24 Shifts"),
                    ("12/48 SHIFT", "12/48 Shifts"),
                    ("24/72 SHIFT, STANDBY SERVICE", "24/72 Shift, Standby Service"),
                    ("STUDENT WORK", "Student Work"),
                    ("REMOTE WORK", "Remote work"),
                    ("HOME OFFICE", "Home office"),
                    ("ON_SITE", "On-site"),
                    ("HYBRID", "Hybrid"),
                ]
            ),
        ),
    ]
