# Generated by Django 4.2.3 on 2024-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0019_employmentschedulechoice_and_more"),
        ("job_post", "0020_alter_jobpost_work_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="work_schedule",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="work_schedule",
            field=models.ManyToManyField(
                blank=True, to="profile.employmentschedulechoice"
            ),
        ),
    ]
