# Generated by Django 4.2.3 on 2024-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile",
            "0021_drivinglicensechoice_remove_profile_driving_licence_and_more",
        ),
        ("job_post", "0021_remove_jobpost_work_schedule_jobpost_work_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="driving_licence",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="driving_license",
            field=models.ManyToManyField(blank=True, to="profile.drivinglicensechoice"),
        ),
    ]
