# Generated by Django 4.2.3 on 2024-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0022_workingtimechoice_remove_profile_working_time_and_more"),
        ("job_post", "0022_remove_jobpost_driving_licence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="working_time",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="working_time",
            field=models.ManyToManyField(blank=True, to="profile.workingtimechoice"),
        ),
    ]
