# Generated by Django 4.2.3 on 2024-08-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0023_educationchoice"),
        ("job_post", "0023_remove_jobpost_working_time_jobpost_working_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="educations",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="educations",
            field=models.ManyToManyField(blank=True, to="profile.educationchoice"),
        ),
    ]
