# Generated by Django 4.2.3 on 2024-08-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0025_category_subcategory_remove_jobpost_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_job_posts",
                to="job_post.category",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_job_posts",
                to="job_post.subcategory",
            ),
        ),
    ]
