# Generated by Django 4.2.3 on 2024-10-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0027_category_featured_category_icon_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostapplication",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
