# Generated by Django 4.2.3 on 2024-10-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0028_jobpostapplication_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostapplication",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
