# Generated by Django 4.2.3 on 2025-01-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0029_jobpostapplication_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobpostapplication",
            options={"ordering": ["is_read", "-created_at"]},
        ),
    ]
