# Generated by Django 4.2.11 on 2025-03-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0030_alter_jobpostapplication_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
