# Generated by Django 4.2.11 on 2025-03-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0031_jobpost_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="created_by",
        ),
    ]
