# Generated by Django 4.2.11 on 2025-03-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0032_remove_jobpost_created_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequiredLanguageKnowledge",
        ),
    ]
