# Generated by Django 4.2.11 on 2025-03-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0034_jobpost_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredLanguageKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Arabic", "Arabic"),
                            ("Bengali", "Bengali"),
                            ("Bulgarian", "Bulgarian"),
                            ("Chinese", "Chinese"),
                            ("Croatian", "Croatian"),
                            ("Czech", "Czech"),
                            ("Danish", "Danish"),
                            ("Dutch", "Dutch"),
                            ("English", "English"),
                            ("Estonian", "Estonian"),
                            ("Finnish", "Finnish"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Greek", "Greek"),
                            ("Hindi", "Hindi"),
                            ("Hungarian", "Hungarian"),
                            ("Irish", "Irish"),
                            ("Italian", "Italian"),
                            ("Japanese", "Japanese"),
                            ("Latvian", "Latvian"),
                            ("Lithuanian", "Lithuanian"),
                            ("Malay", "Malay"),
                            ("Maltese", "Maltese"),
                            ("Polish", "Polish"),
                            ("Portuguese", "Portuguese"),
                            ("Punjabi", "Punjabi"),
                            ("Romanian", "Romanian"),
                            ("Slovak", "Slovak"),
                            ("Slovenian", "Slovenian"),
                            ("Spanish", "Spanish"),
                            ("Swedish", "Swedish"),
                            ("Urdu", "Urdu"),
                        ]
                    ),
                ),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ]
                    ),
                ),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_languages",
                        to="job_post.jobpost",
                    ),
                ),
            ],
        ),
    ]
