# Generated by Django 4.2.11 on 2025-03-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0035_requiredlanguageknowledge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requiredlanguageknowledge",
            name="job_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_languages",
                to="job_post.jobpost",
            ),
        ),
        migrations.AlterField(
            model_name="requiredlanguageknowledge",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arabic", "Arabic"),
                    ("Bengali", "Bengali"),
                    ("Bulgarian", "Bulgarian"),
                    ("Chinese", "Chinese"),
                    ("Croatian", "Croatian"),
                    ("Czech", "Czech"),
                    ("Danish", "Danish"),
                    ("Dutch", "Dutch"),
                    ("English", "English"),
                    ("Estonian", "Estonian"),
                    ("Finnish", "Finnish"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Greek", "Greek"),
                    ("Hindi", "Hindi"),
                    ("Hungarian", "Hungarian"),
                    ("Irish", "Irish"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Latvian", "Latvian"),
                    ("Lithuanian", "Lithuanian"),
                    ("Malay", "Malay"),
                    ("Maltese", "Maltese"),
                    ("Polish", "Polish"),
                    ("Portuguese", "Portuguese"),
                    ("Punjabi", "Punjabi"),
                    ("Romanian", "Romanian"),
                    ("Slovak", "Slovak"),
                    ("Slovenian", "Slovenian"),
                    ("Spanish", "Spanish"),
                    ("Swedish", "Swedish"),
                    ("Urdu", "Urdu"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="requiredlanguageknowledge",
            name="level",
            field=models.TextField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                null=True,
            ),
        ),
    ]
