# Generated by Django 4.2.11 on 2025-03-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0036_alter_requiredlanguageknowledge_job_post_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="is_contact_email_public",
        ),
    ]
