# Generated by Django 5.1 on 2025-03-30 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0038_remove_jobpost_is_contact_phone_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostLocationChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Job Location Choice",
                "verbose_name_plural": "Job Location Choices",
            },
        ),
        migrations.AddField(
            model_name="jobpost",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_job_posts",
                to="job_post.jobpostlocationchoice",
            ),
        ),
    ]
