# Generated by Django 5.1 on 2025-03-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0039_jobpostlocationchoice_jobpost_location"),
        ("profile", "0054_languageknowledge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="location",
        ),
        migrations.RenameField(
            model_name="jobpost",
            old_name="work_place_address",
            new_name="job_address",
        ),
        migrations.RenameField(
            model_name="jobpost",
            old_name="work_place_city",
            new_name="job_city",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="work_place_country",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="job_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_location_job_posts",
                to="profile.joblocationchoice",
            ),
        ),
        migrations.DeleteModel(
            name="JobPostLocationChoice",
        ),
    ]
