# Generated by Django 5.1 on 2025-04-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0040_remove_jobpost_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="boost_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="boost_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homepage", "Főoldal"),
                    ("banner", "Banner"),
                    ("sidebar", "Oldalsáv"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="boost_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="expiration_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="is_boosted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="reminder_days_before_expiry",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="title_editable_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
