# Generated by Django 5.1 on 2025-04-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0041_jobpost_boost_end_date_jobpost_boost_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Listing"),
                            ("homepage", "Homepage Boost"),
                            ("banner", "Banner Boost"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="jobpost",
            name="selected_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job_post.jobplan",
            ),
        ),
    ]
