# Generated by Django 5.1 on 2025-04-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0042_jobplan_jobpost_selected_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobplan",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
    ]
