# Generated by Django 5.1 on 2025-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0043_jobplan_is_recommended"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="billing_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="billing_city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="billing_country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="billing_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="billing_state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="billing_tax_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="billing_zip_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
