# Generated by Django 5.1 on 2025-04-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0044_jobpost_billing_address_jobpost_billing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Checkout Session ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="stripe_customer_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address used for Stripe payment",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe PaymentIntent ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="stripe_transaction_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when Stripe checkout.session.completed was received",
                null=True,
            ),
        ),
    ]
