# Generated by Django 5.1 on 2025-04-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0045_jobpost_stripe_checkout_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="stripe_customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="stripe_transaction_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
