# Generated by Django 4.2.3 on 2024-04-05 08:52
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [TrigramExtension()]
