# Generated by Django 4.2.3 on 2024-04-05 08:52

import apps.profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company_information", models.TextField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        null=True,
                        upload_to=apps.profile.models.upload_to_profile_folder,
                    ),
                ),
                (
                    "company_file",
                    models.FileField(
                        null=True,
                        upload_to=apps.profile.models.upload_to_profile_folder,
                    ),
                ),
                (
                    "contact_name_and_position",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "cv",
                    models.FileField(
                        null=True,
                        upload_to=apps.profile.models.upload_to_profile_folder,
                    ),
                ),
                (
                    "cover_letter",
                    models.FileField(
                        null=True,
                        upload_to=apps.profile.models.upload_to_profile_folder,
                    ),
                ),
                (
                    "is_contact_private",
                    models.BooleanField(
                        default=False,
                        help_text="If checked only your username show up in chats",
                    ),
                ),
                (
                    "is_address_private",
                    models.BooleanField(
                        default=False,
                        help_text="If checked your address won't show up on your profile page",
                    ),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "address_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postcode", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "blocked_companies",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("still_there", models.BooleanField(default=False)),
                ("main_tasks", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LanguageKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=255)),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ]
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
