# Generated by Django 4.2.3 on 2024-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_address_private",
            field=models.BooleanField(
                default=False,
                help_text="If checked your address won't show up on your profile page",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_contact_private",
            field=models.BooleanField(
                default=False,
                help_text="If checked only your username show up in chats",
                null=True,
            ),
        ),
    ]
