# Generated by Django 4.2.3 on 2024-04-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profile", "0002_alter_profile_is_address_private_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="postcode",
            new_name="address_postcode",
        ),
        migrations.AlterField(
            model_name="profile",
            name="blocked_companies",
            field=models.ManyToManyField(
                blank=True, related_name="blocking_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
