# Generated by Django 4.2.3 on 2024-04-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_alter_languageknowledge_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_date_of_birth_private",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="job_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=255)),
                (
                    "degree",
                    models.CharField(help_text="Ex. Bachelor's", max_length=255),
                ),
                ("field_of_study", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("in_progress", models.BooleanField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
        ),
    ]
