# Generated by Django 4.2.3 on 2024-04-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="profile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="languageknowledge",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages_known",
                to="profile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to="profile.profile",
            ),
        ),
    ]
