# Generated by Django 4.2.3 on 2024-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_alter_education_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="driving_licence",
            field=models.TextField(
                blank=True,
                choices=[
                    ("B", "B"),
                    ("BE", "BE"),
                    ("A", "A"),
                    ("A1", "A1"),
                    ("C1", "C1"),
                    ("C1E", "C1E"),
                    ("CE", "CE"),
                    ("D1", "D1"),
                    ("D1E", "D1E"),
                    ("D", "D"),
                    ("DE", "DE"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GENERAL WORKING SCHEDULE", "GENERAL WORKING SCHEDULE"),
                    ("2 SHIFTS", "2 SHIFTS"),
                    ("3 SHIFTS", "3 SHIFTS"),
                    ("12/48 SHIFT", "12/48 SHIFT"),
                    ("12/24 SHIFT", "12/24 SHIFT"),
                    ("24/72 SHIFT, STANDBY SERVICE", "24/72 SHIFT, STANDBY SERVICE"),
                    ("FLEXIBILE", "FLEXIBILE"),
                    ("CONTINUOUS WORKING TIME", "CONTINUOUS WORKING TIME"),
                    ("OPTIONAL WORKING HOURS", "OPTIONAL WORKING HOURS"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="working_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL TIME", "Full time"),
                    ("PART TIME", "Part time"),
                    ("REMOTE WORK", "Remote work"),
                    ("HOME OFFICE", "Home office"),
                    ("CASUAL", "Casual"),
                    ("PROFESSIONAL PRACTICE", "Professional practice"),
                    ("STUDENT WORK", "Student work"),
                    (
                        "FOR MOTHERS AND / OR SINGLE PARENTS",
                        "For mother and / or single parents",
                    ),
                    (
                        "IN PENSION, WORK NEXT TO RETIRED",
                        "In pension, work next to retired",
                    ),
                    (
                        "FOR CHANGED EMPLOYMENT CAPACITY",
                        "For changed employment capacity",
                    ),
                ],
                null=True,
            ),
        ),
    ]
