# Generated by Django 4.2.3 on 2024-04-19 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_profile_driving_licence_profile_work_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
