# Generated by Django 4.2.3 on 2024-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_alter_profile_work_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                choices=[
                    ("ELEMENTARY", "Elementary"),
                    ("SECONDARY", "Secondary"),
                    ("HIGHSCHOOL", "HighSchool"),
                    ("BSC", "Bsc"),
                    ("MSC", "Msc"),
                    ("PHD", "Phd"),
                ],
                help_text="Ex. Bachelor's",
            ),
        ),
    ]
