# Generated by Django 4.2.3 on 2024-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0011_profile_profile_picture_alter_education_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="public_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
