# Generated by Django 4.2.3 on 2024-07-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0012_profile_public_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="areas_of_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRAINED_UNSKILLED_WORKERS", "Trained or Unskilled Jobs"),
                    ("TRANSPORTATION", "Transportation"),
                    ("WAREHOUSE", "Warehouse"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headquarters",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="internal_communication_languages",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arabic", "Arabic"),
                    ("Bengali", "Bengali"),
                    ("Bulgarian", "Bulgarian"),
                    ("Chinese", "Chinese"),
                    ("Croatian", "Croatian"),
                    ("Czech", "Czech"),
                    ("Danish", "Danish"),
                    ("Dutch", "Dutch"),
                    ("English", "English"),
                    ("Estonian", "Estonian"),
                    ("Finnish", "Finnish"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Greek", "Greek"),
                    ("Hindi", "Hindi"),
                    ("Hungarian", "Hungarian"),
                    ("Irish", "Irish"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Latvian", "Latvian"),
                    ("Lithuanian", "Lithuanian"),
                    ("Malay", "Malay"),
                    ("Maltese", "Maltese"),
                    ("Polish", "Polish"),
                    ("Portuguese", "Portuguese"),
                    ("Punjabi", "Punjabi"),
                    ("Romanian", "Romanian"),
                    ("Slovak", "Slovak"),
                    ("Slovenian", "Slovenian"),
                    ("Spanish", "Spanish"),
                    ("Swedish", "Swedish"),
                    ("Urdu", "Urdu"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="main_of_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCOUNTANCY", "Accountancy & Finance"),
                    ("AGRICULTURE_ENVIRONMENT", "Agriculture, Environment"),
                    ("APPRENTICESHIP", "Apprenticeship, Internship"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="number_of_employees",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "None"),
                    ("1-10", "1 to 10 employees"),
                    ("11-20", "11 to 20 employees"),
                    ("21-50", "21 to 50 employees"),
                    ("51-100", "51 to 100 employees"),
                    ("100+", "More than 100 employees"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="year_of_foundation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
