# Generated by Django 4.2.3 on 2024-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0013_profile_areas_of_activity_profile_headquarters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="headquarters",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
