# Generated by Django 4.2.3 on 2024-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0014_alter_profile_headquarters"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profession",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
