# Generated by Django 4.2.3 on 2024-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0015_profile_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REMOTE", "Remote"),
                    ("ON_SITE", "On-site"),
                    ("HYBRID", "Hybrid"),
                ],
                null=True,
            ),
        ),
    ]
