# Generated by Django 4.2.3 on 2024-07-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0016_profile_job_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="areas_of_activity",
            new_name="sub_activity",
        ),
    ]
