# Generated by Django 4.2.3 on 2024-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0018_alter_profile_main_of_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentScheduleChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="work_schedule",
        ),
        migrations.AddField(
            model_name="profile",
            name="work_schedule",
            field=models.ManyToManyField(
                blank=True, to="profile.employmentschedulechoice"
            ),
        ),
    ]
