# Generated by Django 4.2.3 on 2024-08-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0019_employmentschedulechoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="internal_communication_languages",
        ),
        migrations.AddField(
            model_name="profile",
            name="internal_communication_languages",
            field=models.ManyToManyField(blank=True, to="profile.languagechoice"),
        ),
    ]
