# Generated by Django 4.2.3 on 2024-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile",
            "0021_drivinglicensechoice_remove_profile_driving_licence_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingTimeChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="working_time",
        ),
        migrations.AddField(
            model_name="profile",
            name="working_time",
            field=models.ManyToManyField(blank=True, to="profile.workingtimechoice"),
        ),
    ]
