# Generated by Django 4.2.3 on 2024-08-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0024_joblocationchoice_remove_profile_job_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employmentschedulechoice",
            options={
                "verbose_name": "Employment Schedule Choice",
                "verbose_name_plural": "Employment Schedule Choices",
            },
        ),
        migrations.AddField(
            model_name="employmentschedulechoice",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employmentschedulechoice",
            name="name_hu",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
