# Generated by Django 4.2.3 on 2024-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0026_alter_drivinglicensechoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="achievement",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="introduction",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="qualification",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
