# Generated by Django 4.2.3 on 2024-08-06 15:04

import apps.profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0028_cv_coverletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="cover_letter_file",
            field=models.FileField(
                upload_to=apps.profile.models.upload_to_profile_cover_letter_folder
            ),
        ),
        migrations.AlterField(
            model_name="cv",
            name="cv_file",
            field=models.FileField(
                upload_to=apps.profile.models.upload_to_profile_cv_folder
            ),
        ),
    ]
