# Generated by Django 4.2.3 on 2024-08-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0029_alter_coverletter_cover_letter_file_alter_cv_cv_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="cover_letter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="cv",
        ),
    ]
