# Generated by Django 4.2.3 on 2024-08-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0031_alter_education_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
