# Generated by Django 4.2.3 on 2024-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0033_activity_subactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="name_hu",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subactivity",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subactivity",
            name="name_hu",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
