# Generated by Django 4.2.3 on 2024-08-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0034_activity_name_en_activity_name_hu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="main_of_activity",
        ),
        migrations.AddField(
            model_name="profile",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_profile",
                to="profile.activity",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sub_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_activity_profile",
                to="profile.subactivity",
            ),
        ),
    ]
