# Generated by Django 4.2.3 on 2024-08-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0036_numberofworkerchoice_profile_number_of_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="number_of_employees",
        ),
    ]
