# Generated by Django 4.2.3 on 2024-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0039_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cv",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
