# Generated by Django 4.2.3 on 2024-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0040_coverletter_is_public_cv_is_public_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="name",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cv",
            name="name",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
