# Generated by Django 4.2.3 on 2024-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0041_alter_coverletter_name_alter_cv_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
