# Generated by Django 4.2.3 on 2024-10-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0042_alter_coverletter_name_alter_cv_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="company_file",
        ),
    ]
