# Generated by Django 4.2.3 on 2024-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0043_remove_profile_company_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="company_phone",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_contact_email_public",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_contact_phone_public",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
