# Generated by Django 4.2.3 on 2024-11-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0044_rename_company_phone_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_contact_email_public",
            new_name="is_contact_phone_private",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_contact_phone_public",
        ),
    ]
