# Generated by Django 4.2.3 on 2024-11-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile",
            "0045_rename_is_contact_email_public_profile_is_contact_phone_private_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-in_progress", "-start_date", "-end_date"],
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ["-start_date"]},
        ),
    ]
