# Generated by Django 4.2.3 on 2025-01-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0048_coverletter_language_cv_language_document_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="is_sendable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cv",
            name="is_sendable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="is_sendable",
            field=models.BooleanField(default=False),
        ),
    ]
