# Generated by Django 4.2.3 on 2025-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0049_coverletter_is_sendable_cv_is_sendable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
