# Generated by Django 4.2.11 on 2025-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0050_profile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
