# Generated by Django 4.2.11 on 2025-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0051_alter_coverletter_is_public_alter_cv_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
