# Generated by Django 4.2.11 on 2025-03-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0052_profile_company_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LanguageKnowledge",
        ),
    ]
