# Generated by Django 5.1 on 2025-03-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_post", "0040_remove_jobpost_location_and_more"),
        ("profile", "0054_languageknowledge"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobLocationChoice",
            new_name="LocationChoice",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address_city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address_postcode",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_address",
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_city",
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_location",
                to="profile.locationchoice",
            ),
        ),
    ]
