# Generated by Django 5.1 on 2025-03-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0055_rename_joblocationchoice_locationchoice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverletter",
            name="is_sendable",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="is_sendable",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_sendable",
        ),
    ]
