# Generated by Django 5.1 on 2025-04-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0058_profile_billing_address_profile_billing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="billing_state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="billing_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="billing_city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="billing_country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="billing_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="billing_tax_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="billing_zip_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
