# Generated by Django 5.1 on 2025-04-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile",
            "0059_profile_billing_state_alter_profile_billing_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_state",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_tax_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="billing_zip_code",
        ),
    ]
