# Generated by Django 5.1 on 2025-04-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0060_remove_profile_billing_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="contact_name_and_position",
        ),
    ]
