from django.db import models
from django.utils.translation import gettext_lazy as _

class LanguageKnowledgeLevelChoices(models.TextChoices):
    A1 = "A1", _("A1")
    A2 = "A2", _("A2")
    B1 = "B1", _("B1")
    B2 = "B2", _("B2")
    C1 = "C1", _("C1")
    C2 = "C2", _("C2")

class AvailableLanguageChoices(models.TextChoices):
    ENGLISH = "ENGLISH", _("English")
    DUTCH = "DUTCH", _("Dutch")
    GERMAN = "GERMAN", _("German")
    HUNGARIAN = "HUNGARIAN", _("Hungarian")

class LanguageChoices(models.TextChoices):
    Arabic = "Arabic", _("Arabic")
    Bengali = "Bengali", _("Bengali")
    Bulgarian = "Bulgarian", _("Bulgarian")
    Chinese = "Chinese", _("Chinese")
    Croatian = "Croatian", _("Croatian")
    Czech = "Czech", _("Czech")
    Danish = "Danish", _("Danish")
    Dutch = "Dutch", _("Dutch")
    English = "English", _("English")
    Estonian = "Estonian", _("Estonian")
    Finnish = "Finnish", _("Finnish")
    French = "French", _("French")
    German = "German", _("German")
    Greek = "Greek", _("Greek")
    Hindi = "Hindi", _("Hindi")
    Hungarian = "Hungarian", _("Hungarian")
    Irish = "Irish", _("Irish")
    Italian = "Italian", _("Italian")
    Japanese = "Japanese", _("Japanese")
    Latvian = "Latvian", _("Latvian")
    Lithuanian = "Lithuanian", _("Lithuanian")
    Malay = "Malay", _("Malay")
    Maltese = "Maltese", _("Maltese")
    Polish = "Polish", _("Polish")
    Portuguese = "Portuguese", _("Portuguese")
    Punjabi = "Punjabi", _("Punjabi")
    Romanian = "Romanian", _("Romanian")
    Slovak = "Slovak", _("Slovak")
    Slovenian = "Slovenian", _("Slovenian")
    Spanish = "Spanish", _("Spanish")
    Swedish = "Swedish", _("Swedish")
    Urdu = "Urdu", _("Urdu")
