# Generated by Django 4.2.11 on 2025-03-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_read_by_alter_chatmessage_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
