# Generated by Django 5.1 on 2025-04-09 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatmessage_chatroom_delete_chat_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_room", "timestamp"], name="chat_chatme_chat_ro_f45542_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["receiver", "is_read"], name="chat_chatme_receive_d79e66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender"], name="chat_chatme_sender__3a9411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["last_message_time"], name="chat_chatro_last_me_f04f57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_private_chat"
            ),
        ),
    ]
