# Generated by Django 5.1 on 2025-04-09 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatroom_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
    ]
